# Generated by Django 6.0.3 on 2026-03-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermandad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('templo', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(default='Antigua Guatemala', max_length=120)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descripcion_corta', models.TextField(blank=True)),
                ('color_primario', models.CharField(default='#111111', max_length=20)),
                ('color_acento', models.CharField(default='#b08d57', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hermandad',
                'verbose_name_plural': 'Hermandades',
                'ordering': ['nombre'],
            },
        ),
    ]
