# Generated by Django 6.0.3 on 2026-03-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hermandad',
            options={},
        ),
        migrations.AddField(
            model_name='hermandad',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hermandad',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hermandad',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hermandad',
            name='ciudad',
            field=models.CharField(default='Antigua Guatemala', max_length=100),
        ),
        migrations.AlterField(
            model_name='hermandad',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hermandad',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='TurnoRecorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre_turno', models.CharField(max_length=200)),
                ('pieza', models.CharField(max_length=200)),
                ('genero', models.CharField(blank=True, max_length=100)),
                ('compositor', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('orden_ruta', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_recorrido', to='hermandades.hermandad')),
            ],
            options={
                'ordering': ['numero', 'orden_ruta'],
                'unique_together': {('hermandad', 'numero', 'orden_ruta')},
            },
        ),
    ]
