# Generated by Django 6.0.3 on 2026-08-04 18:22

import django.core.validators
import hermandades.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandades', '0004_seguridad_contenido_devotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermandad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[hermandades.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='hermandad',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/', validators=[hermandades.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='imagenhermandad',
            name='imagen',
            field=models.ImageField(upload_to='galeria/', validators=[hermandades.validators.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='marchaprocesional',
            name='audio',
            field=models.FileField(blank=True, upload_to='marchas/', validators=[hermandades.validators.validate_audio_size, django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'ogg', 'wav'])]),
        ),
    ]
