# Generated by Django 6.0.6 on 2026-08-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandades', '0011_comunicaciones_sms_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermandad',
            name='imagen_templo',
            field=models.ImageField(blank=True, null=True, upload_to='templos/', verbose_name='Imagen del templo'),
        ),
    ]
