# Generated by Django 6.0.6 on 2026-08-31 18:20

import django.core.validators
import hermandades.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandades', '0012_hermandad_imagen_templo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohermandad',
            name='video',
            field=models.FileField(blank=True, help_text='Puedes subir un video directamente. Formatos permitidos: MP4, WEBM, MOV y M4V.', null=True, upload_to='videos/', validators=[hermandades.validators.validate_video_size, django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])], verbose_name='archivo de video'),
        ),
        migrations.AlterField(
            model_name='videohermandad',
            name='url',
            field=models.URLField(blank=True, help_text='Opcional. Enlace de YouTube o Vimeo. Utilízalo si no vas a subir un archivo de video.'),
        ),
    ]
